const { sequelize } = require('./src/config/database');

(async () => {
    try {
        await sequelize.authenticate();
        console.log("Connected to DB.");
        const [results] = await sequelize.query("SHOW INDEX FROM Users");

        // Identify indexes to drop
        // We want to keep 'PRIMARY', 'roleId', 'admittedProgramId', and the base unique ones like 'email', 'username', 'studentId'
        // We want to drop anything that looks like 'email_2', 'username_5', 'studentId_12', etc.

        const indexesToDrop = [];
        const keep = ['PRIMARY', 'roleId', 'admittedProgramId', 'email', 'username', 'studentId', 'users_studentId_unique'];

        results.forEach(row => {
            const name = row.Key_name;
            if (keep.includes(name)) return;

            // Heuristic: if it ends in _number, likely a duplicate generated by sequelize
            if (name.match(/_\d+$/)) {
                if (!indexesToDrop.includes(name)) {
                    indexesToDrop.push(name);
                }
            }
        });

        console.log("Indexes to drop:", indexesToDrop);

        if (indexesToDrop.length === 0) {
            console.log("No duplicate indexes found to drop.");
        } else {
            for (const indexName of indexesToDrop) {
                console.log(`Dropping index: ${indexName}`);
                try {
                    await sequelize.query(`DROP INDEX \`${indexName}\` ON Users`);
                } catch (e) {
                    console.error(`Failed to drop ${indexName}: ${e.message}`);
                }
            }
            console.log("Done dropping indexes.");
        }

    } catch (error) {
        console.error("Error:", error.message);
    } finally {
        await sequelize.close();
    }
})();
